// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { ToastContainer } from 'react-toastify';
import { ReactNode } from 'react'; // এটি টাইপ ডিফাইন করার জন্য লাগবে

import Navbar from "@/components/Navbar";
import Manubar from "@/components/Manubar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "BUDGETPRO",
    template: "%s | BUDGETPRO",
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} bg-gray-100 antialiased`}>
          
            {/* Logged in → Dashboard layout */}
            <SignedIn>
              <Navbar />
              <div className="flex">
                <Toaster richColors />
                <ToastContainer/>
                <Manubar />
                <div className="flex-1">{children}</div>
              </div>
            </SignedIn>

            {/* Logged out → Landing page */}
            <SignedOut>{children}</SignedOut>
          
        </body>
      </html>
    </ClerkProvider>
  );
}